/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.panel.nhanvien;

import com.nhsys.dao.HoaDonDAO;
import com.nhsys.entity.HoaDon;
import com.nhsys.panel.quanly.NV_XemMon;
import com.nhsys.utils.XImage;

import java.awt.Color;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Hai Tran
 */
public class NV_SoDoBan extends javax.swing.JPanel {

    void xemMon(String soBan, JButton bt) {
        //khi click vào nút bàn trên giao diện -> lấy text của button -> truyền qua form xemMon
        if (bt.getBackground().getRGB() != -1) {
            new NV_XemMon(soBan).setVisible(true);
        }

    }

    public NV_SoDoBan() {
        initComponents();
        XImage.setHinh(lblBackground, "logos\\SoDoBan.jpg", lblBackground.getWidth(), lblBackground.getHeight());
        fillButtonBan();
    }

    public static void fillButtonBan() {
        //dshd = danh sách hóa đơn
//        List<HoaDon> DSHD = new HoaDonDAO().selectAllProc("Chưa Thanh toán");
//        for (HoaDon hd : DSHD) {
//            switch (hd.getSoBan()) {
//                case "B01":
//                    btnB01.setBackground(new Color(255, 153, 51));
//                    btnB01.setForeground(Color.white);
//                    break;
//                case "B02":
//                    btnB02.setBackground(new Color(255, 153, 51));
//                    btnB02.setForeground(Color.white);
//                    break;
//                case "B03":
//                    btnB03.setBackground(new Color(255, 153, 51));
//                    btnB03.setForeground(Color.white);
//                    break;
//                case "B04":
//                    btnB04.setBackground(new Color(255, 153, 51));
//                    btnB04.setForeground(Color.white);
//                    break;
//                case "B05":
//                    btnB05.setBackground(new Color(255, 153, 51));
//                    btnB05.setForeground(Color.white);
//                    break;
//                case "B06":
//                    btnB06.setBackground(new Color(255, 153, 51));
//                    btnB06.setForeground(Color.white);
//                    break;
//                case "B07":
//                    btnB07.setBackground(new Color(255, 153, 51));
//                    btnB07.setForeground(Color.white);
//                    break;
//                case "B08":
//                    btnB08.setBackground(new Color(255, 153, 51));
//                    btnB08.setForeground(Color.white);
//                    break;
//                case "B09":
//                    btnB09.setBackground(new Color(255, 153, 51));
//                    btnB09.setForeground(Color.white);
//                    break;
//                case "B10":
//                    btnB10.setBackground(new Color(255, 153, 51));
//                    btnB10.setForeground(Color.white);
//                    break;
//                case "B11":
//                    btnB11.setBackground(new Color(255, 153, 51));
//                    btnB11.setForeground(Color.white);
//                    break;
//                case "B12":
//                    btnB12.setBackground(new Color(255, 153, 51));
//                    btnB12.setForeground(Color.white);
//                    break;
//                case "B13":
//                    btnB13.setBackground(new Color(255, 153, 51));
//                    btnB13.setForeground(Color.white);
//                    break;
//                case "B14":
//                    btnB14.setBackground(new Color(255, 153, 51));
//                    btnB14.setForeground(Color.white);
//                    break;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        jPanel3.setLayout(null);
        jPanel3.add(lblBackground);
        lblBackground.setBounds(-9, -4, 1120, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
