/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.panel.nhanvien;

import com.nhsys.dao.HoaDonDAO;
import com.nhsys.panel.quanly.NV_XemMon;
import com.nhsys.utils.XImage;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Hai Tran
 */
public class NV_SoDoBan extends javax.swing.JPanel {

    void xemMon(String soBan, JButton bt) {
        //khi click vào nút bàn trên giao diện -> lấy text của button -> truyền qua form xemMon
        if (bt.getBackground().getRGB() != -1) {
            new NV_XemMon(soBan).setVisible(true);
        }

    }

    public NV_SoDoBan() {
        initComponents();
        XImage.setHinh(lblBackground, "logos\\Sodoban.jpg", lblBackground.getWidth(), lblBackground.getHeight());
//        fillButtonBan();
    }

//    public static void fillButtonBan() {
//        //dshd = danh sách hóa đơn
//        List<HoaDon> DSHD = new HoaDonDAO().selectAllProc("Chưa Thanh toán");
//        for (HoaDon hd : DSHD) {
//            switch (hd.getSoBan()) {
//                case "B01":
//                    btnB01.setBackground(new Color(255, 153, 51));
//                    btnB01.setForeground(Color.white);
//                    break;
//                case "B02":
//                    btnB02.setBackground(new Color(255, 153, 51));
//                    btnB02.setForeground(Color.white);
//                    break;
//                case "B03":
//                    btnB03.setBackground(new Color(255, 153, 51));
//                    btnB03.setForeground(Color.white);
//                    break;
//                case "B04":
//                    btnB04.setBackground(new Color(255, 153, 51));
//                    btnB04.setForeground(Color.white);
//                    break;
//                case "B05":
//                    btnB05.setBackground(new Color(255, 153, 51));
//                    btnB05.setForeground(Color.white);
//                    break;
//                case "B06":
//                    btnB06.setBackground(new Color(255, 153, 51));
//                    btnB06.setForeground(Color.white);
//                    break;
//                case "B07":
//                    btnB07.setBackground(new Color(255, 153, 51));
//                    btnB07.setForeground(Color.white);
//                    break;
//                case "B08":
//                    btnB08.setBackground(new Color(255, 153, 51));
//                    btnB08.setForeground(Color.white);
//                    break;
//                case "B09":
//                    btnB09.setBackground(new Color(255, 153, 51));
//                    btnB09.setForeground(Color.white);
//                    break;
//                case "B10":
//                    btnB10.setBackground(new Color(255, 153, 51));
//                    btnB10.setForeground(Color.white);
//                    break;
//                case "B11":
//                    btnB11.setBackground(new Color(255, 153, 51));
//                    btnB11.setForeground(Color.white);
//                    break;
//                case "B12":
//                    btnB12.setBackground(new Color(255, 153, 51));
//                    btnB12.setForeground(Color.white);
//                    break;
//                case "B13":
//                    btnB13.setBackground(new Color(255, 153, 51));
//                    btnB13.setForeground(Color.white);
//                    break;
//                case "B14":
//                    btnB14.setBackground(new Color(255, 153, 51));
//                    btnB14.setForeground(Color.white);
//                    break;
//            }
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnB01 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnB2 = new javax.swing.JButton();

        jPanel3.setLayout(null);

        btnB01.setBackground(new java.awt.Color(255, 255, 255));
        btnB01.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnB01.setForeground(new java.awt.Color(255, 153, 0));
        btnB01.setText("B01");
        btnB01.setMaximumSize(new java.awt.Dimension(50, 50));
        btnB01.setMinimumSize(new java.awt.Dimension(50, 50));
        btnB01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB01ActionPerformed(evt);
            }
        });
        jPanel3.add(btnB01);
        btnB01.setBounds(40, 180, 90, 80);
        jPanel3.add(lblBackground);
        lblBackground.setBounds(-9, -4, 1140, 620);

        btnB2.setBackground(new java.awt.Color(255, 255, 255));
        btnB2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnB2.setForeground(new java.awt.Color(255, 153, 0));
        btnB2.setText("B01");
        btnB2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnB2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnB2);
        btnB2.setBounds(40, 40, 90, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnB01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB01ActionPerformed
        // TODO add your handling code here:
        xemMon("B01", btnB01);
    }//GEN-LAST:event_btnB01ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnB01;
    public static javax.swing.JButton btnB2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
