/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhsys.ui;

import com.nhsys.dao.DanhMucDAO;
import com.nhsys.entity.DanhMuc;
import com.nhsys.utils.MsgBox;
import com.nhsys.utils.mouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhha
 */
public class QL_DanhMucJPN extends javax.swing.JPanel {

    /**
     * Creates new form QL_DanhMucJPN
     */
    public QL_DanhMucJPN() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtMadanhmuc = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogoMaDM = new javax.swing.JLabel();
        txtTendanhmuc = new javax.swing.JTextField();
        lblLogoTenDM = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblLogoMT = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhMuc = new javax.swing.JTable();
        cboSXtheoten = new javax.swing.JComboBox<>();
        txtTimtheotendm = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1109, 593));
        setMinimumSize(new java.awt.Dimension(1109, 593));
        setPreferredSize(new java.awt.Dimension(1109, 593));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        btnThem.setBackground(new java.awt.Color(0, 153, 204));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem);

        btnXoa.setBackground(new java.awt.Color(0, 153, 204));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa);

        btnSua.setBackground(new java.awt.Color(0, 153, 204));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua);

        btnMoi.setBackground(new java.awt.Color(0, 153, 204));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel3.add(btnMoi);

        txtMadanhmuc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMadanhmuc.setText("Mã Danh Mục");
        txtMadanhmuc.setBorder(null);
        txtMadanhmuc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMadanhmucFocusLost(evt);
            }
        });
        txtMadanhmuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMadanhmucMouseClicked(evt);
            }
        });

        lblLogoMaDM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/coding.png"))); // NOI18N

        txtTendanhmuc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTendanhmuc.setText("Tên Danh Mục");
        txtTendanhmuc.setBorder(null);
        txtTendanhmuc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTendanhmucFocusLost(evt);
            }
        });
        txtTendanhmuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTendanhmucMouseClicked(evt);
            }
        });

        lblLogoTenDM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/coding.png"))); // NOI18N

        lblLogoMT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhsys/icon/coding.png"))); // NOI18N

        txtMota.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMota.setText("Mô Tả");
        txtMota.setBorder(null);
        txtMota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMotaFocusLost(evt);
            }
        });
        txtMota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMotaMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        btnFirst.setBackground(new java.awt.Color(0, 0, 0));
        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel4.add(btnFirst);

        btnPrev.setBackground(new java.awt.Color(0, 0, 0));
        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrev);

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel4.add(btnNext);

        btnLast.setBackground(new java.awt.Color(0, 0, 0));
        btnLast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel4.add(btnLast);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogoTenDM)
                        .addGap(16, 16, 16)
                        .addComponent(txtTendanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogoMT)
                        .addGap(16, 16, 16)
                        .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogoMaDM)
                        .addGap(16, 16, 16)
                        .addComponent(txtMadanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoMaDM)
                    .addComponent(txtMadanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoTenDM)
                    .addComponent(txtTendanhmuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoMT)
                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        tabs.addTab("Cập nhật", jPanel1);

        tblDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MaDanhMuc", "TenDanhMuc", "MoTa"
            }
        ));
        tblDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhMucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhMuc);

        cboSXtheoten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp theo tên", "Từ A -> Z", "Từ Z -> A" }));
        cboSXtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSXtheotenActionPerformed(evt);
            }
        });

        txtTimtheotendm.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        txtTimtheotendm.setText("Nhập tên danh mục cần tìm");
        txtTimtheotendm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimtheotendmFocusLost(evt);
            }
        });
        txtTimtheotendm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimtheotendmMouseClicked(evt);
            }
        });
        txtTimtheotendm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimtheotendmKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboSXtheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(txtTimtheotendm, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                        .addGap(409, 409, 409))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSXtheoten, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimtheotendm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabs.addTab("Danh Sách", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtMadanhmucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMadanhmucFocusLost
        new mouseEvent().clear_text_exit(txtMadanhmuc, "Mã Danh Mục");
    }//GEN-LAST:event_txtMadanhmucFocusLost

    private void txtMadanhmucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMadanhmucMouseClicked
        new mouseEvent().clear_text_click(txtMadanhmuc, "Mã Danh Mục");
    }//GEN-LAST:event_txtMadanhmucMouseClicked

    private void txtTendanhmucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTendanhmucFocusLost
        new mouseEvent().clear_text_exit(txtTendanhmuc, "Tên Danh Mục");
    }//GEN-LAST:event_txtTendanhmucFocusLost

    private void txtTendanhmucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTendanhmucMouseClicked
        new mouseEvent().clear_text_click(txtTendanhmuc, "Mã Danh Mục");
    }//GEN-LAST:event_txtTendanhmucMouseClicked

    private void txtMotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMotaFocusLost
        new mouseEvent().clear_text_exit(txtMota, "Tên Danh Mục");
    }//GEN-LAST:event_txtMotaFocusLost

    private void txtMotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMotaMouseClicked
        new mouseEvent().clear_text_click(txtMota, "Mã Danh Mục");
    }//GEN-LAST:event_txtMotaMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (!checkVal()) {
            return;
        }
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhMucMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblDanhMuc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblDanhMucMouseClicked

    private void cboSXtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSXtheotenActionPerformed
        // TODO add your handling code here:
        if (cboSXtheoten.getSelectedIndex() == 1) {
            fillTableOrderA();
        } else if (cboSXtheoten.getSelectedIndex() == 2) {
            fillTableOrderD();
        } else {
            fillTable();
        }
    }//GEN-LAST:event_cboSXtheotenActionPerformed

    private void txtTimtheotendmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimtheotendmFocusLost
        // TODO add your handling code here:
        new mouseEvent().clear_text_exit(txtTimtheotendm, "Nhập tên danh mục cần tìm");
    }//GEN-LAST:event_txtTimtheotendmFocusLost

    private void txtTimtheotendmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimtheotendmMouseClicked
        // TODO add your handling code here:
        new mouseEvent().clear_text_click(txtTimtheotendm, "Nhập tên danh mục cần tìm");
    }//GEN-LAST:event_txtTimtheotendmMouseClicked

    private void txtTimtheotendmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimtheotendmKeyPressed
        // TODO add your handling code here:
        fillTableByName();
    }//GEN-LAST:event_txtTimtheotendmKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboSXtheoten;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLogoMT;
    private javax.swing.JLabel lblLogoMaDM;
    private javax.swing.JLabel lblLogoTenDM;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDanhMuc;
    private javax.swing.JTextField txtMadanhmuc;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtTendanhmuc;
    private javax.swing.JTextField txtTimtheotendm;
    // End of variables declaration//GEN-END:variables

    DanhMucDAO dao = new DanhMucDAO();
    int row = -1;
    
    void init() {
        tblDanhMuc.setDefaultEditor(Object.class, null);
        this.fillTable(); // đổ dữ liệu nhân viên vào bảng
        this.updateStatus(); // cập nhật trạng thái form
        clearForm();
    }
    
    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblDanhMuc.getRowCount() - 1);
        // Trạng thái form
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        btnMoi.setEnabled(edit);

//        // Trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }
    
    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0);
        try {
            List<DanhMuc> list = dao.selectAll();
            for (DanhMuc dm : list) {
                Object[] row = {
                    dm.getMaDanhmuc(),
                    dm.getTenDanhmuc(),
                    dm.getMoTa()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void fillTableByName() {
        String Chuoitimkiem = txtTimtheotendm.getText();
        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0);
        try {
            List<DanhMuc> list = dao.timNhanVienTheoTenDM(Chuoitimkiem);
            for (DanhMuc dm : list) {
                Object[] row = {
                    dm.getMaDanhmuc(),
                    dm.getTenDanhmuc(),
                    dm.getMoTa()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void fillTableOrderA() {
        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0);
        try {
            List<DanhMuc> list = dao.selectByOrderA();
            for (DanhMuc dm : list) {
                Object[] row = {
                    dm.getMaDanhmuc(),
                    dm.getTenDanhmuc(),
                    dm.getMoTa()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }
    
    void fillTableOrderD() {
        DefaultTableModel model = (DefaultTableModel) tblDanhMuc.getModel();
        model.setRowCount(0);
        try {
            List<DanhMuc> list = dao.selectByOrderD();
            for (DanhMuc dm : list) {
                Object[] row = {
                    dm.getMaDanhmuc(),
                    dm.getTenDanhmuc(),
                    dm.getMoTa()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
    }
    
    boolean checkVal() {
        if (txtTendanhmuc.getText().isEmpty() || txtTendanhmuc.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập tên danh mục!");
            return false;
        } else if (txtMadanhmuc.getText().length() > 15) {
            return false;
        }
        if (txtTendanhmuc.getText().isEmpty() || txtTendanhmuc.getText().equalsIgnoreCase("")) {
            MsgBox.alert(this, "Bạn chưa nhập tên danh mục!");
            return false;
        }
        return true;
    }
    
    void insert() {
        DanhMuc dm = this.getForm();
        try {
            dao.insert(dm); // thêm mới
            this.fillTable(); // đỗ lại bảng
            this.clearForm(); // xóa trắng form
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }
    
    void update() {
        DanhMuc dm = this.getForm();
        try {
            dao.update(dm); // cập nhật
            this.fillTable(); // đổ lại bảng
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }
    
    void delete() {
        String madm = txtMadanhmuc.getText();
        try {
            dao.delete(madm);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Xóa thất bại!");
        }
    }
    
    void edit() {
        String madm = (String) tblDanhMuc.getValueAt(this.row, 0);
        DanhMuc dm = dao.selectById(madm);
        this.setForm(dm);
        this.updateStatus();
        tabs.setSelectedIndex(0);
    }
    
    void first() {
        this.row = 0;
        this.edit();
    }
    
    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }
    
    void next() {
        if (this.row < tblDanhMuc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }
    
    void last() {
        this.row = tblDanhMuc.getRowCount() - 1;
        this.edit();
    }
    
    void clearForm() {
        DanhMuc dm = new DanhMuc();
        this.setForm(dm);
        this.row = -1;
        this.updateStatus();
    }
    
    void setForm(DanhMuc dm) {
        txtMadanhmuc.setText(dm.getMaDanhmuc());
        txtTendanhmuc.setText(dm.getTenDanhmuc());
        txtMota.setText(dm.getMoTa());
    }
    
    DanhMuc getForm() {
        DanhMuc dm = new DanhMuc();
        dm.setMaDanhmuc(txtMadanhmuc.getText());
        dm.setTenDanhmuc(txtTendanhmuc.getText());
        dm.setMoTa(txtMota.getText());
        return dm;
    }
}
